### ISSUE TITLE
 DLL file not found

### ISSUE THREAD

**Issue by AnnaZhaoZhao** [Telecommunication-Telemedia-Assessment/bitstream_mode3_p1204_3#22]
hello， when I run:
`poetry run p1204_3 test_videos/test_video_h265.mkv `
it throw an error :
ERROR:root:video parser is not build correctly, please check
Traceback (most recent call last):
  File "/mnt/disk/wpt/bitstream_mode3_p1204_3/p1204_3/bitstream_mode3_videoparser/PythonInterface/parse.py"ne 78, in <module>
    main()
  File "/mnt/disk/wpt/bitstream_mode3_p1204_3/p1204_3/bitstream_mode3_videoparser/PythonInterface/parse.py"ne 59, in main
    video_parser = videoparser.VideoParser(a["input"], a["dll"])
  File "/mnt/disk/wpt/bitstream_mode3_p1204_3/p1204_3/bitstream_mode3_videoparser/PythonInterface/lib/videoer.py", line 15, in __init__
    self.parser = pi.ParserInterface(self.input_file, dll_path)
  File "/mnt/disk/wpt/bitstream_mode3_p1204_3/p1204_3/bitstream_mode3_videoparser/PythonInterface/lib/parseerface.py", line 17, in __init__
    raise IOError("DLL file not found")
OSError: DLL file not found
ERROR:root:there was something wrong with test_videos/test_video_h265.mkv
ERROR:root:please check the following command:
 /mnt/disk/wpt/bitstream_mode3_p1204_3/p1204_3/bitstream_mode3_videoparser/parser.sh "test_videos/test_vide65.mkv" --output "./tmp/test_video_h265.json.bz2"
ERROR:root:no bitstream stats file for test_videos/test_video_h265.mkv
[
    {}
]

then, when I run:
` /mnt/disk/wpt/bitstreambitstream_mode3_videoparser/parser.sh "test_videos/test_video_h265.mkv" --output "./tmp/test_video_h265.json.bz2`
it shows:
Traceback (most recent call last):
  File "/mnt/disk/fengpf/wpt/bitstream_mode3_p1204_3/p1204_3/bitstream_mode3_videoparser/PythonInterface/parse.py"
    main()
  File "/mnt/disk/fengpf/wpt/bitstream_mode3_p1204_3/p1204_3/bitstream_mode3_videoparser/PythonInterface/parse.py"
    video_parser = videoparser.VideoParser(a["input"], a["dll"])
  File "/mnt/disk/fengpf/wpt/bitstream_mode3_p1204_3/p1204_3/bitstream_mode3_videoparser/PythonInterface/lib/video __init__
    self.parser = pi.ParserInterface(self.input_file, dll_path)
  File "/mnt/disk/fengpf/wpt/bitstream_mode3_p1204_3/p1204_3/bitstream_mode3_videoparser/PythonInterface/lib/parse, in __init__
    raise IOError("DLL file not found")
OSError: DLL file not found

so, what DLL file should I add? Looking forward to your reply.

**Comment by AnnaZhaoZhao** [comment]
> Traceback (most recent call last): File "/mnt/disk/fengpf/wpt/bitstream_mode3_p1204_3/p1204_3/bitstream_mode3_videoparser/PythonInterface/parse.py" main() File "/mnt/disk/fengpf/wpt/bitstream_mode3_p1204_3/p1204_3/bitstream_mode3_videoparser/PythonInterface/parse.py" video_parser = videoparser.VideoParser(a["input"], a["dll"]) File "/mnt/disk/fengpf/wpt/bitstream_mode3_p1204_3/p1204_3/bitstream_mode3_videoparser/PythonInterface/lib/video __init__ self.parser = pi.ParserInterface(self.input_file, dll_path) File "/mnt/disk/fengpf/wpt/bitstream_mode3_p1204_3/p1204_3/bitstream_mode3_videoparser/PythonInterface/lib/parse, in __init__ raise IOError("DLL file not found") OSError: DLL file not found

**Comment by AnnaZhaoZhao** [comment]
> 
Traceback (most recent call last):
  File "/mnt/disk/fengpf/wpt/bitstream_mode3_p1204_3/p1204_3/bitstream_mode3_videoparser/PythonInterface/parse.py"
    main()
  File "/mnt/disk/fengpf/wpt/bitstream_mode3_p1204_3/p1204_3/bitstream_mode3_videoparser/PythonInterface/parse.py"
    video_parser = videoparser.VideoParser(a["input"], a["dll"])
  File "/mnt/disk/fengpf/wpt/bitstream_mode3_p1204_3/p1204_3/bitstream_mode3_videoparser/PythonInterface/lib/video __init__
    self.parser = pi.ParserInterface(self.input_file, dll_path)
  File "/mnt/disk/fengpf/wpt/bitstream_mode3_p1204_3/p1204_3/bitstream_mode3_videoparser/PythonInterface/lib/parse, in __init__
    raise IOError("DLL file not found")
OSError: DLL file not found

**Comment by slhck** [comment]
Please go to:

    /mnt/disk/wpt/bitstream_mode3_p1204_3/p1204_3/bitstream_mode3_videoparser

And check if the command `./build.sh` succeeds.

Specifically, after building, the file `/VideoParser/libvideoparser.so` must exist.

**Comment by AnnaZhaoZhao** [comment]
thank you, it's been successful! it was because I had not install the dependencies correctly.

**Comment by slhck** [comment]
Glad I could help!
